# General options for the bot
[general]
  # Insert your Bot Token here!
  # DO NOT SHARE IT WITH ANYONE!
  botToken = "Mzk0NTkxMDgyMDMxMjE4Njk4.WkARlQ.0sfYECB34cHMDRc7uAFiOJdy8UI"
  # The channel ID where the bot will be working in
  botChannel = "536609070119911445"
  # The bot's status message
  # 
  # PLACEHOLDERS:
  # %online% - Online Players
  # %max% - Maximum Player Amount
  botStatusName = "%online% players Online"
  # Type of the bot's status
  # Allowed Values: DISABLED,PLAYING,WATCHING,LISTENING
  botStatusType = "PLAYING"
  # Enable checking for updates?
  # Notification will be shown after every server start in log when update is available
  enableUpdateChecker = true
  # The minimum release type for the update checker to notify
  # Allowed values: release, beta, alpha
  updateCheckerMinimumReleaseType = "beta"
# Configuration options for commands
[commands]
  # The Role IDs of your Admin Roles
  # Now supports multiple roles which can access admin commands
adminRoleIDs = [    ]
  # The prefix of the commands usable in discord
  prefix = "/"
  # Set to true to require an space after the prefix (e.g. 'mc help')
  spaceAfterPrefix = false
  # Add your Custom commands to this JSON
  # You can copy-paste it to https://jsoneditoronline.org  Make sure when pasting here, that the json is NOT mulitlined.
  # You can click on "Compact JSON Data" on the website
  # NOTE: The JSON string must be escaped. You can use this website to escape or unescape: https://www.freeformatter.com/java-dotnet-escape.html
  # 
  # mcCommand   -   The command to execute on the server. use %args% to place the arguments inside of the command
  # adminOnly   -   True: Only allows users with the Admin role to use this command. False: @everyone can use the command
  # description -   Description shown in /help
  # aliases     -   Aliases for the command in a string array
  # useArgs     -   Shows argument text after the command in the help command
  # argText     -   Defines custom arg text. Default is <args>
  # channelIDs  -   Allows you to set specific text channels outside of the server channel to use this command (make it an string array), Set to ["00"] to allow from all channels
  customCommandJSON = "{\"kick\":{\"adminOnly\":true,\"mcCommand\":\"kick\",\"description\":\"Kicks a player from the server\",\"useArgs\":true,\"argText\":\"<player> [reason]\"},\"stop\":{\"adminOnly\":true,\"mcCommand\":\"stop\",\"description\":\"Stops the server\",\"aliases\":[\"shutdown\"],\"useArgs\":false},\"kill\":{\"adminOnly\":true,\"mcCommand\":\"kill\",\"description\":\"Kills a player\",\"useArgs\":true,\"argText\":\"<player>\"},\"tps\":{\"adminOnly\":false,\"mcCommand\":\"forge tps\",\"description\":\"Displays TPS\",\"useArgs\":false}}"
  # You must op this UUID in the ops.txt or some custom commands won't work!
  senderUUID = "8d8982a5-8cf9-4604-8feb-3dd5ee1f83a3"
  # Enable help command?
  # Disabling also removes response when you entered an invalid command
  # Requires server restart
  helpCmdEnabled = true
  # Enable the list command in discord
  # Requires server restart
  listCmdEnabled = true
  # Enable the uptime command in discord
  # Requires server restart
  uptimeCmdEnabled = true
  # Set to false to completely disable the "Unknown Command" message
  showUnknownCommandMessage = true
  # Set to true to enable the "Unknown Command" message in all channels
  showUnknownCommandEverywhere = false
# Everything message related
[messages]
  # Enable formatting conversion (Markdown <==> Minecraft)
  convertCodes = true
  # Send formatting codes from mc chat to discord
  # Has no effect when markdown <==> Minecraft is enabled
  formattingCodesToDiscord = false
  # Should /say output be sent to discord?
  sendOnSayCommand = true
  # Should /me output be sent to discord?
  sendOnMeCommand = true
  # When an /say command's message starts with this prefix, it will not be sent to discord
  sayCommandIgnoredPrefix = "§4§6§k§r"
  # Should tamed entity death be visible in discord?
  sendDeathMessagesForTamedAnimals = false
# Advanced options
[advanced]
  # Custom channel ID for server specific messages (like Join/leave)
  # Leave 'default' to use default channel
  serverChannelID = "default"
  # Custom channel ID for death messages
  # Leave 'default' to use default channel
  deathsChannelID = "default"
  # Custom channel for for ingame messages
  # Leave 'default' to use default channel
  chatOutputChannelID = "default"
  # Custom channel where messages get sent to minecraft
  # Leave 'default' to use default channel
  chatInputChannelID = "default"
  # Custom Channel ID list for the help command. Set to 00 to allow usage from everywhere and to 0 to allow usage from the bots default channel
helpCmdChannelIDs = [  "0"  ]
  # Custom Channel ID list for the list command. Set to 00 to allow usage from everywhere and to 0 to allow usage from the bots default channel
listCmdChannelIDs = [  "0"  ]
  # Custom Channel ID list for the uptime command. Set to 00 to allow usage from everywhere and to 0 to allow usage from the bots default channel
uptimeCmdChannelIDs = [  "0"  ]
# Config options which only have an effect when using forge
[forgeSpecific]
  # A list of blacklisted modids
  # Adding one will prevent the mod to send messages to discord using forges IMC system
IMC_modIdBlacklist = [  "examplemod"  ]
  # Show item information, which is visible on hover ingame, as embed in discord?
  sendItemInfo = true
# Configuration for linking
[linking]
  # Should discord linking be enabled?
  # If whitelist is on, this can NOT be disabled
  # DOES NOT WORK IN OFFLINE MODE!
  enableLinking = true
  # Role ID of an role an player should get when he links his discord account
  # Leave as 0 to disable
  linkedRoleID = "0"
  # Enable discord based whitelist?
  # This will override the link config!
  # To whitelist use !whitelist <uuid> in the bot DMs
  whitelistMode = false
  # Adding Role IDs here will require the players to have at least ONE of these roles to link account
requiredRoles = [    ]
# Webhook configuration
[webhook]
  # Whether or not the bot should use a webhook (it will create one)
  enable = false
  # The avatar to be used for server messages
  serverAvatarURL = "https://raw.githubusercontent.com/ErdbeerbaerLP/Discord-Chat-Integration/master/images/srv.png"
  # The name to be used for server messages
  serverName = "Minecraft Server"
  # The URL where the player avatar gets fetched from
  # 
  # PLACEHOLDERS:
  # %uuid% - Returns the player's UUID with dashes
  # %uuid_dashless% - Returns the player's UUID without dashes
  # %name% - Returns the player's name
  # %randomUUID% - Returns an random UUID which can be used to prevent discord cache
  playerAvatarURL = "https://minotar.net/avatar/%uuid%?randomuuid=%randomUUID%"
# Allows you to modify and translate most of the messages this bot will send
[localization]
  # This is what will be displayed ingame when someone types into the bot's channel
  # PLACEHOLDERS:
  # %user% - The username
  # %id% - The user ID
  # %msg% - The Message
  ingame_discordMessage = "§6[§5DISCORD§6]§r <%user%> %msg%"
  # This message will edited in / sent when the server finished starting
  serverStarted = "Server Started!"
  # Message to show while the server is starting
  # This will be edited to SERVER_STARTED_MSG when webhook is false
  serverStarting = "Server Starting..."
  # This message will be sent when the server was stopped
  serverStopped = "Server Stopped!"
  # The message to print to discord when it was possible to detect a server crash
  serverCrash = "Server Crash Detected :thinking:"
  # Gets sent when an player joins
  # 
  # PLACEHOLDERS:
  # %player% - The player's name
  playerJoin = "%player% joined"
  # Gets sent when an player leaves
  # 
  # PLACEHOLDERS:
  # %player% - The player's name
  playerLeave = "%player% left"
  # Gets sent when an player dies
  # 
  # PLACEHOLDERS:
  # %player% - The player's name
  # %msg% - The death message
  playerDeath = "%player% %msg%"
  # Message sent instead of playerLeave, when the player times out
  # 
  # PLACEHOLDERS:
  # %player% - The player's name
  playerTimeout = "%player% timed out!"
  # Gets sent when an player finishes an advancement
  # Supports MulitLined messages using \n
  # 
  # PLACEHOLDERS:
  # %player% - The player's name
  # %name% - The advancement name
  # %desc% - The advancement description
  advancementMessage = "%player% just made the advancement **%name%**\\\n_%desc%_"
  # The chat message in discord, sent from an player in-game
  # 
  # PLACEHOLDERS:
  # %player% - The player's name
  # %msg% - The chat message
  discordChatMessage = "%player%: %msg%"
  # Message sent when ignoring Discord messages
  commandIgnore_ignore = "You are now ignoring Discord messages!"
  # Message sent when unignoring Discord messages
  commandIgnore_unignore = "You are no longer ignoring Discord messages!"
  # The format of the uptime command
  # For more help with the formatting visit https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/DurationFormatUtils.html
  uptimeFormat = "dd 'days' HH 'hours' mm 'minutes'"
  # Sent to the user when he linked his discord successfully
  # PLACEHOLDERS:
  # %player% - The in-game player name
  # %prefix% - Command prefix
  linkSuccessful = "Your account is now linked with %player%.\nUse %prefix%settings here to view and set some user-specific settings"
  # Sent to the user when linking fails
  linkFailed = "Account link failed"
  # Sent when an already linked user attempts to link an account
  # PLACEHOLDERS:
  # %player% - The in-game player name
  alreadyLinked = "Your account is already linked with %player%"
  # Sent when attempting to use personal commands while not linked
  # PLACEHOLDERS:
  # %method% - The currently enabled method for linking
  notLinked = "Your account is not linked! Link it first using %method%"
  # Message of the link method in whitelist mode
  # Used by %method% placeholder
  linkMethodWhitelist = "`%prefix%whitelist <uuid>` here"
  # Message of the link method in normal mode
  # Used by %method% placeholder
  linkMethodIngame = "`/discord link` ingame"
  # Sent when attempting to whitelist-link with an non uuid string
  # PLACEHOLDERS:
  # %arg% - The provided argument
  # %prefix% - Command prefix
  link_argumentNotUUID = "Argument \"%arg%\" is not an valid UUID. Use `%prefix%whitelist <uuid>`"
  # Sent when attempting to link with an unknown number
  invalidLinkNumber = "Invalid link number! Use `/discord link` ingame to get your link number"
  # Sent when attempting to link with an invalid number
  linkNumberNAN = "This is not a number. Use `/discord link` ingame to get your link number"
  # Header of the personal settings list
  personalSettingsHeader = "Personal Settings list:"
  # Error message when providing an invalid personal setting name
  invalidPersonalSettingKey = "`%key%` is not an valid setting!"
  # Message for getting an setting's value
  personalSettingGet = "This settings value is `%bool%`"
  # Sent when user sucessfully updates an prersonal setting
  settingUpdateSuccessful = "Successfully updated setting!"
  # Sent when setting an personal setting fails
  settingUpdateFailed = "Failed to set value :/"
  # Message sent when user does not have permission to run a command
  noPermission = "You don't have permission to execute this command!"
  # Message sent when an invalid command was typed
  # 
  # PLACEHOLDERS:
  # %prefix% - Command prefix
  unknownCommand = "Unknown command, try `%prefix%help` for a list of commands"
  # Message if a player provides less arguments than required
  notEnoughArguments = "Not enough arguments"
  # Message if a player provides too many arguments
  tooManyArguments = "Too many arguments"
  # Message if a player can not be found
  # 
  # PLACEHOLDERS:
  # %player% - The player's name
  playerNotFound = "Can not find player \"%player%\""
  # The message for 'list' when no player is online
  cmdList_empty = "There is no player online..."
  # The header for 'list' when one player is online
  cmdList_one = "There is 1 player online:"
  # The header for 'list'
  # PLACEHOLDERS:
  # %amount% - The amount of players online
  cmdList_header = "There are %amount% players online:"
  # Header of the help command
  cmdHelp_header = "Your available commands in this channel:"
  # Message shown to players who are not whitelisted using discord
  # No effect if discord whitelist is off
  notWhitelisted = "§cYou are not whitelisted.\nJoin the discord server for more information\nhttps://discord.gg/someserver"
  # Sent when trying to link without an required role
  link_requiredRole = "You need to have an role to use this"
  # Sent when trying to link as an non-member
  link_notMember = "You are not member of the Discord-Server this bot is operating in!"
# Configuration for the in-game command '/discord'
[ingameCommand]
  # Enable the /discord command to show an custom message with invite URL?
  enabled = true
  # The message displayed when typing /discord in the server chat
  message = "Join our discord! http://discord.gg/myserver"
  # The message shown when hovering the /discord command message
  hoverMessage = "Click to open the invite url"
  # The url to open when clicking the /discord command text
  inviteURL = "http://discord.gg/myserver"
# The command log channel is an channel where every command execution gets logged
[commandLog]
  # Channel ID for the command log channel
  # Leave 0 to disable
  channelID = "0"
  # The format of the log messages
  # 
  # PLACEHOLDERS:
  # %sender% - The name of the Command Source
  # %cmd% - executed command (e.g. "/say Hello World"
  # %cmd-no-args% - Command without arguments (e.g. "/say"
  message = "%sender% executed command `%cmd%`"
